version: "3.7"

services:  
  mongodb:
    container_name: mongodb
    hostname: mongodb
    # build: ./backend/mongodb
    image: "mongo:4.1"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

    
volumes:
  mongodb_data: